### ISSUE TITLE
[tracker] Migrate code from tsdb-proxy java

### ISSUE THREAD

**Issue by at15** [at15/reika#1]
Currently Reika lies in https://github.com/xephonhq/tsdb-proxy-java , it should be a project of its own and imported in tsdb-proxy-java(go) as a library for query and benchmark. Also we can't just copy the code or use git subtree, clean up need to be done and existing git history is not that useful.

Tooling

- [x] re structure the folder 
- [ ] list detail plan
- [x] doc for tracking issue and progress along side github issues
- [ ] github issue labels and templates, milestone, project etc.
- [x] setup travis
- [ ] setup lint
  - https://www.codacy.com/ seems have used it before 
  - https://codecov.io used when writing hadoop assignments https://github.com/at15/forum-search, but it seems old report is not stored 
  - https://coveralls.io old UI, but works fine
  - https://codebeat.co/ too strict, always say my go code have too many instance variables ....

Code

- [x] migrate the parser and interpreter

Extra

- [ ] formalize the process and templates for starting and planning a new project, and apply it to other projects I am working on, notably xephon-k, gommon and Ayi
  - cadvisor's issues label explanation https://github.com/google/cadvisor/blob/master/docs/development/issues.md

**Comment by at15** [comment]
For folder structure, had a look at https://github.com/collections/programming-languages, might follow scala's

````
doc (actually there are just license file in it ....)
spec
test
scripts
tools
````

**Comment by at15** [comment]
need to do it later, have a lot more things to do before submitting the report ... report driven development

**Comment by at15** [comment]
the report is submitted ... resume
